apiVersion: batch/v1
kind: Job
metadata:
  name: studreum-richards-celia-run41
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: studreum-laplace-container
          image: lsx-stud-registry.informatik.uni-wuerzburg.de/studreum/pytorch-laplace:0.0.6
          imagePullPolicy: "IfNotPresent"
          env:
            - name: EPOCHES
              value: "1e9"
            - name: HYPERTRIALS
              value: "20"
            - name: DIVISIONS
              value: "400"
            - name: HIDDEN
              value: "10"
            - name: NEURONS
              value: "40"
            - name: LR
              value: ".001"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: "256Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: "128Gi"
          volumeMounts:
            - mountPath: /home/stud/reum # directory IN the container
              name: localdir # matches volume-name from below
          command: ["/bin/sh","-c"]
          # args: ["cd /home/stud/reum/runs/richards-celia/run41; python3 -m richards_celia"]
          args: ["cd /home/stud/reum/runs/richards-celia/run41; python3 -m richards_celia"]
      imagePullSecrets:
        - name: lsx-registry
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studreum  # <namespace>
            path: "/home/stud/reum" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
