apiVersion: batch/v1
kind: Job
metadata:
  name: studreum-laplace_v2-run4
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: studreum-laplace_v2-container
          image: lsx-stud-registry.informatik.uni-wuerzburg.de/studreum/pytorch-laplace_v2:0.0.4
          imagePullPolicy: "IfNotPresent"
          env:
            - name: EPOCHES
              value: "1e6"
            - name: HIDDEN
              value: "8"
            - name: DIVISIONS
              value: "32"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "256Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "256Gi"
          volumeMounts:
            - mountPath: /home/stud/reum # directory IN the container
              name: localdir # matches volume-name from below
          command: ["/bin/sh","-c"]
          args: ["cd /home/stud/reum/laplace_v2/run4; python3 -m laplace_v2"]
      imagePullSecrets:
        - name: lsx-registry
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studreum  # <namespace>
            path: "/home/stud/reum" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret